spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/beekeeper
    username: postgres
    password: root
    default-schema: beekeeper
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    default-schema: beekeeper
server:
  port: 8083
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      name: house
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.json.JsonSerializer
kafka:
  topic: beehouse
  message: 'Hello from the beehouse!'
  publish-rate: 60000 # publish every minute