spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLCDB
    username: system
    password: 1789Yvan
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
server:
  port : 8081