spring:
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/ORCLCDB
    username: system
    password: 1789Yvan
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
server:
  port : 8083
  kafka:
    bootstrap-servers: localhost:9092
    topic:
      name: house
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.json.JsonSerializer
kafka:
  topic: beehouse
  message: 'Hello from the beehouse!'
  publish-rate: 60000 # publish every minute
